### PR TITLE
Group 32 001

### PR DESCRIPTION
**Pull request by Bakhtiar-Semseddin**
it is bakhtiyar

### CODE REVIEW

**Comment by innurur** [comment]
hi

**Comment by Bakhtiar-Semseddin** [comment]
hello

**Comment by innurur** [comment]
Cool. So I can see your code here

**Comment by Bakhtiar-Semseddin** [comment]
yes me too

**Comment by Nazikallaberdiyeva** [comment]
So cool!

**Comment by innurur** [comment]
Who else can join us?

**Pull request merged**
